import React from 'react';
import Head from 'next/head';

type Props = {
    children: React.ReactNode;
    title?: string;
}

const MainLayout = (props: Props) => {
    return (
        <div>
            <Head>
                <title>{props?.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div>
                    {props.children}
                </div>
            </main>
        </div>
    )
}

export const getMainLayout = (page: React.ReactElement, title?: string) => (
    <MainLayout title={title}>{page}</MainLayout>
)

export default MainLayout